logging:
  level: DEBUG
  loggers:
    io.dropwizard: DEBUG
    org.eclipse.jetty: INFO
    com.hubspot.dropwizard.guicier.GuiceBundle: INFO
    org.apache.http: INFO
server:
  type: default
  maxThreads: 25
  rootPath: /test-api